### ISSUE TITLE
Нужны отдельные методы на like/dislike

### ISSUE THREAD

**Issue by coursar** [azatmagdeev/likerBackend#5]

**Comment by azatmagdeev** [comment]
@coursar , сделать чтобы лайк/дизлайк считались на бэкенде?
или чтобы просто обновлялись с фронтенда?

**Comment by coursar** [comment]
Чтобы считались на бэкенде: делаете post mems/<id>/likes - лайки увеличиваются, delete mems/<id>/likes - уменьшаются.

**Comment by azatmagdeev** [comment]
@coursar 
добавил like/dislike
